// @title Zest DSL
// @description Zest's native template language is real F#. This page is a real .zest.fsx script evaluated by FSI at build time.
// @category dsl
// @tags dsl, fsharp
// @date 2026-08-01
//
// Content-page scripts receive the site context (Context.get()) but not a
// `page` binding — layouts are the only place that binding exists. The body
// below is rendered by FSI and wrapped by the F# docs layout.

open Zest.Dsl

/// Render a code sample with the CSS language label used by the theme.
let codeSample (lang: string) (code: string) =
    elem "pre" [] [ elem "code" [ cls ("language-" + lang) ] [ raw code ] ]

let helloSource =
    """render [
    h1 [ text "Hello, world" ]
    p  [ text "Pages: " ; strong [ text "42" ] ]
    a  "/posts/" [ text "Read the posts" ]
]"""

let loopSource =
    """site_pages ()
|> Array.filter (fun p -> p.category <> "" && p.url.StartsWith "/en/")
|> Array.sortBy (fun p -> p.slug)
|> Array.truncate 6
|> Array.map (fun p -> li [ a [ href p.url ] [ text p.title ] ])
|> Array.toList
|> ul"""

render [
    h1 [ text "Zest DSL" ]
    p [
        text "Zest's native template language is real F#. A "
        code [ text ".zest.fsx" ]
        text " page is a script evaluated by F# Interactive at build time: the DSL helpers compose HTML as strings, and "
        code [ text "render" ]
        text " prints the result to stdout. You get types, autocomplete and full IDE support — and the engine stays boring: it just captures the script's output."
    ]
    h2 [ text "Composition" ]
    p [ text "Elements are plain functions over string children:" ]
    codeSample "fsharp" helloSource
    h2 [ text "Pipelines over site data" ]
    p [
        text "DslCollections exposes the whole site as typed records, so data transforms are ordinary F# pipelines. This very list is generated by the script shown below:"
    ]
    codeSample "fsharp" loopSource
    h2 [ text "Live result" ]
    p [ text "Six docs pages pulled from the build context:" ]
    (site_pages ()
     |> Array.filter (fun p -> p.category <> "" && p.url.StartsWith "/en/")
     |> Array.sortBy (fun p -> p.slug)
     |> Array.truncate 6
     |> Array.map (fun p -> li [ elem "a" [ href p.url ] [ text p.title ] ])
     |> Array.toList
     |> ul)
    h2 [ text "Helpers" ]
    p [
        text "Beyond the element builders there are shortcuts for common patterns — "
        code [ text "divC" ]
        text ", "
        code [ text "aC" ]
        text ", "
        code [ text "ulC" ]
        text ", "
        code [ text "jsonBlock" ]
        text " for injecting typed data into client JS, "
        code [ text "js" ]
        text " for inline script blocks, and "
        code [ text "t_lang" ]
        text " for locale lookups. See the DSL reference for the full list."
    ]
]
